# Copyright 2008 - 2017 Hitachi Vantara.  All rights reserved. 
# This program is free software; you can redistribute it and/or modify it under the
# terms of the GNU Lesser General Public License, version 2.1 as published by the Free Software
# Foundation.
#
# You should have received a copy of the GNU Lesser General Public License along with this
# program; if not, you can obtain a copy at http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
# or from the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Lesser General Public License for more details.
#SampleData/type=javax.sql.DataSource
#SampleData/driver=org.postgresql.jdbcDriver
#SampleData/url=jdbc:postgresql://localhost:5432/hibernate
#SampleData/user=hibuser
#SampleData/password=password
Hibernate/type=javax.sql.DataSource
Hibernate/driver=org.postgresql.jdbcDriver
Hibernate/url=jdbc:postgresql://localhost:5432/hibernate
Hibernate/user=hibuser
Hibernate/password=password
Quartz/type=javax.sql.DataSource
Quartz/driver=org.postgresql.jdbcDriver
Quartz/url=jdbc:postgresql://localhost:5432/quartz
Quartz/user=pentaho_user
Quartz/password=password
#Shark/type=javax.sql.DataSource
#Shark/driver=org.postgresql.jdbcDriver
#Shark/url=jdbc:postgresql://localhost:5432/hibernate
#Shark/user=hibuser
#Shark/password=password
#SampleDataAdmin/type=javax.sql.DataSource
#SampleDataAdmin/driver=org.postgresql.jdbcDriver
#SampleDataAdmin/url=jdbc:postgresql://localhost:5432/hibernate
#SampleDataAdmin/user=hibuser
#SampleDataAdmin/password=password
